/* CONVERSÃO DE DADOS */
SELECT 1 + '1' /*= 2 - AQUI O + SOMOU */

SELECT '1' + '1' /*= 11 - AQUI O + CONCATENOU AS STRINGS*/

SELECT 'CURSO' + 1

SELECT 'CURSO' + '1'

/* FUNÇÕES DE CONVERSÃO DE DADOS */

SELECT CAST('1' AS INT) + CAST('1' AS INT)
GO

/* CONVERSÃO E CONCATENAÇÃO
htts://msdn.microsoft.com/en-us/library/ms191530.aspx
*/

SELECT NOME, 
NASCIMENTO
FROM ALUNO
GO

SELECT NOME, 
DAY(NASCIMENTO) +'/'+ MONTH(NASCIMENTO) +'/'+ YEAR(NASCIMENTO)
FROM ALUNO
GO

SELECT NOME, 
CAST(DAY(NASCIMENTO)AS VARCHAR)  +'/'+ 
CAST(MONTH(NASCIMENTO)AS VARCHAR) +'/'+ 
CAST(YEAR(NASCIMENTO)AS VARCHAR) AS "NASCIMENTO"
FROM ALUNO
GO
