/*BULK INSERT - IMPORTAÇÃO DE ARQUIVOS*/
CREATE TABLE LANCAMENTO_CONTABIL(
	CONTA INT,
	VALOR INT,
	DEB_CRED CHAR(1)
)
GO

SELECT * FROM LANCAMENTO_CONTABIL
GO

BULK INSERT LANCAMENTO_CONTABIL 
FROM 'C:\Users\luiz.paixao\Desktop'
WITH 
(
	FIRSTROW = 2,
	DATAFILETYPE = 'CHAR',
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR = '\n'
)
GO

SELECT * FROM LANCAMENTO_CONTABIL
GO

/*DEPOIS DE APAGAR OS VALORES QUE ESTAO NULOS NO TXT*/
DELETE FROM LANCAMENTO_CONTABIL
GO

/* DESAFIO DO SALDO 
QUERY QUE TRAGA O NÚMERO DA CONTA 
SALDO - DEVEDOR OU CREDOR

USAR SUM. 
*/

SELECT CONTA, VALOR
CHARINDEX('D', DEB_CRED) AS "DEBITO",
CHARINDEX('C', DEB_CRED) AS "CREDITO",
CHARINDEX('C', DEB_CRED) * 2 - 1 AS "MULTIPLICADOR"
FROM LANCAMENTO_CONTABIL
GO

SELECT CONTA, 
SUM(VALOR * (CHARINDEX('C', DEB_CRED) * 2 - 1)) AS "SALDO"
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
GO
