SELECT * FROM PROCESSO

/* CHARINDEX - RETORNA UM INTEIRO
CONTAGEM DEFAULT - INICIA EM 01
*/
SELECT NOME, CHARINDEX('A', NOME) AS INDICE
FROM ALUNO
GO

SELECT NOME, CHARINDEX('A', NOME, 2) AS INDICE
FROM ALUNO
GO
