USE EMPRESA
GO

/* ENDEREÇO */
INSERT INTO ENDERECO VALUES('FLAMENGO', 'RJ', 1)
INSERT INTO ENDERECO VALUES('MORUMBI', 'SP', 2)
INSERT INTO ENDERECO VALUES('CENTRO', 'MG', 4)
INSERT INTO ENDERECO VALUES('MACAÉ', 'RJ', 5)
INSERT INTO ENDERECO VALUES('CENTRO', 'SP', 3)

GO

/* CRIANDO A TABELA TELEFONES - 1xN*/
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT,
	CHECK (TIPO IN('RES','COM','CEL'))
)
GO

INSERT INTO TELEFONE VALUES('CEL','123454657',1)
INSERT INTO TELEFONE VALUES('RES','764321123',1)
INSERT INTO TELEFONE VALUES('COM','765432109',2)
INSERT INTO TELEFONE VALUES('CEL','127634651',2)
GO

SELECT * FROM TELEFONE
GO

/*PEGAR A DATA ATUAL*/
SELECT GETDATE()
GO

/*CLAUSULA AMBIGUA - QUANDO EU FAÇO UM JOIN E TENHO COLUNAS IGUAS EM MAIS DE UMA TABELA*/

SELECT A.NOME, T.TIPO, T.NUMERO, E.BAIRRO, E.UF
FROM ALUNO A LEFT JOIN TELEFONE T
ON A.IDALUNO = T.ID_ALUNO 
LEFT JOIN ENDERECO E
ON A.IDALUNO = T.ID_ALUNO
GO

/* IFNULL */
SELECT  A.NOME, 
		ISNULL(T.TIPO, 'SEM') AS "TIPO",
		ISNULL(T.NUMERO, 'NUMERO') AS "TELEFONE",
		ISNULL(E.BAIRRO, 'BAIRRO') AS "BAIRRO",
		ISNULL(E.UF, 'UF') AS "ESTADO"
FROM ALUNO A LEFT JOIN TELEFONE T
ON A.IDALUNO = T.ID_ALUNO 
LEFT JOIN ENDERECO E
ON A.IDALUNO = T.ID_ALUNO
GO




