USE EMPRESA
GO

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO

/*CONSTRAINTS - REGRA - RESTRIÇÃO*/
ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK(SEXO IN('M','F'))
GO

/* 1 X 1*/
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(20),
	UF CHAR(2) NOT NULL,
	CHECK(UF IN('SP','RJ','MG')),
	ID_ALUNO INT UNIQUE /*A CHAVE DO ALUNO NÃO PODE SE REPETIR NESSA COLUNA PARA TER UM RELACIONAMENTO 1x1 E TER SO UM ENDEREÇO/ALUNO*/	
)
GO

/* CRIANDO A FK - chave estrangeira chamada quando há o relacionamento entre duas tabelas */
ALTER TABLE ENDERECO 
ADD CONSTRAINT FK_ENDERECO_ALUNO FOREIGN KEY(IDALUNO) REFERENCES ALUNO(IDALUNO)
GO

/* COMANDOS DE DESCRIÇÃO*/
/* PROCEDURES - JA CRIADAS E ARMAZENADAS NO SISTEMA*/
/* SP_ DE (STORAGE PROCEDURE)*/
SP_COLUMMS ALUNO /*TRAZ A TABELA COM OS DADOS BEM DETALHADOS*/
GO

SP_HELP /*TRAZ A TABELA BEM MAIS DETALHADA*/
GO

/* INSERINDO DADOS */
INSERT INTO ALUNO VALUES('LUIZ', 'M', '2021/10/02', 'LUIZ@G.COM')
INSERT INTO ALUNO VALUES('LUIZA', 'F', '2022/07/02', 'LUIZA@G.COM')
INSERT INTO ALUNO VALUES('JOAO', 'M', '2023/08/02', 'JOAO@G.COM')
INSERT INTO ALUNO VALUES('MARIO', 'M', '2024/09/02', 'MARIO@G.COM')
INSERT INTO ALUNO VALUES('JULIA', 'F', '2025/11/02', 'JULIA@G.COM')
GO

SELECT * FROM ALUNO
GO
