SELECT * FROM PROCESSO

SELECT NOME, NASCIMENTO
FROM ALUNO
GO

/* DATEDIFF - CALCULA A DIFERENÇA ENTRE DUAS DATAS
FUNÇÃO GETDATE TRAZ DIA E HORA
*/

SELECT NOME, GETDATE() AS DIA_HORA FROM ALUNO
GO

/* 1 PASSO */
SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE())
FROM ALUNO
GO

/*2 PASSO*/
SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE()) AS "IDADE"
FROM ALUNO
GO

/* 3 PASSO - RETORNO INTEIRO + OPERAÇÃO MATEMÁTICA */ 
SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE()/365) AS "IDADE"
FROM ALUNO
GO

SELECT NOME, DATEDIFF(MONTH, NASCIMENTO, GETDATE()/12) AS "IDADE"
FROM ALUNO
GO

SELECT NOME, DATEDIFF(YEAR, NASCIMENTO, GETDATE()) AS "IDADE"
FROM ALUNO
GO

/* DATENAME- TRAZ O NOME DA PARTE DA DATA EM QUESTÃO */
SELECT NOME, DATENAME(MONTH, NASCIMENTO)
FROM ALUNO
GO

/* DATEPART - RETORNA  UM INTEIRO */
SELECT NOME, DATEPART(MONTH, NASCIMENTO)
FROM ALUNO
GO

SELECT NOME, DATEPART(MONTH, NASCIMENTO), DATENAME(MONTH, NASCIMENTO)
FROM ALUNO
GO

/* DATEADD - RETORNA UM DATA SOMANDO A OUTRA DATA */
SELECT DATEADD(DAY, 365, GETDATE())
SELECT DATEADD(YEAR, 10, GETDATE())